== Differences with Clojure

Babashka is implemented using the https://github.com/borkdude/sci[Small
Clojure Interpreter]. This means that a snippet or script is not
compiled to JVM bytecode, but executed form by form by a runtime which
implements a substantial subset of Clojure. Babashka is compiled to a
native binary using https://github.com/oracle/graal[GraalVM]. It comes
with a selection of built-in namespaces and functions from Clojure and
other useful libraries. The data types (numbers, strings, persistent
collections) are the same. Multi-threading is supported (`pmap`,
`future`).

Differences with Clojure:

* A pre-selected set of Java classes are supported. You cannot add Java
classes at runtime.
* Interpretation comes with overhead. Therefore loops are slower than in
Clojure on the JVM. In general interpretation yields slower programs
than compiled programs.
* No `deftype`, `definterface` and unboxed math.
* `defprotocol` and `defrecord` are implemented using multimethods and
regular maps. Ostensibly they work the same, but under the hood there
are no Java classes that correspond to them.
* Currently `reify` works only for one class at a time
* The `clojure.core.async/go` macro is not (yet) supported. For
compatibility it currently maps to `clojure.core.async/thread`. More
info link:#coreasync[here].

== link:doc/projects.md[Libraries, pods and projects]

A list of projects (scripts, libraries, pods and tools) known to work
with babashka.

== Pods

Pods are programs that can be used as a Clojure library by babashka.
Documentation is available in the
https://github.com/babashka/babashka.pods[library repo].

== Package babashka script as a AWS Lambda

AWS Lambda runtime doesn't support signals, therefore babashka has to
disable handling of SIGINT and SIGPIPE. This can be done by setting
`BABASHKA_DISABLE_SIGNAL_HANDLERS` to `true`.

== Articles, podcasts and videos

* https://youtu.be/RogyxI-GaGQ[Writing Clojure on the Command Line with
Babashka], a talk by Nate Jones.
* http://www.karimarttila.fi/clojure/2020/09/01/using-clojure-in-command-line-with-babashka.html[Using
Clojure in Command Line with Babashka], a blog article by Kari Marttila.
* https://youtu.be/3EUMA6bd-xQ[Babashka and GraalVM; taking Clojure to
new places], a talk by Michiel Borkent at
https://www.meetup.com/Clojure-NYC/[Clojure/NYC].
* https://blog.davemartin.me/posts/import-a-csv-into-kafka-using-babashka/[Import
a CSV into Kafka, using Babashka] by Dave Martin
* https://amontalenti.com/2020/07/11/babashka[Learning about babashka],
a blog article by Andrew Montalenti
* https://www.youtube.com/watch?v=3Q4GUiUIrzg&feature=emb_logo[Babashka
Pods] presentation by Michiel Borkent at the
http://meetup.com/The-Dutch-Clojure-Meetup[Dutch Clojure Meetup].
* https://tech.toyokumo.co.jp/entry/aws_logs_babashka[AWS Logs using
Babashka], a blog published by https://toyokumo.co.jp/[Toyokumo].
* https://www.therepl.net/episodes/36/[The REPL podcast] Michiel Borkent
talks about https://github.com/borkdude/clj-kondo[clj-kondo],
https://github.com/borkdude/jet[Jet], Babashka, and
https://github.com/oracle/graal[GraalVM] with Daniel Compton.
* https://youtu.be/0YmZYnwyHHc[Implementing an nREPL server for
babashka]: impromptu presentation by Michiel Borkent at the online
http://meetup.com/The-Dutch-Clojure-Meetup[Dutch Clojure Meetup]
* https://soundcloud.com/user-959992602/s3-e5-babashka-with-michiel-borkent[ClojureScript
podcast] with Jacek Schae interviewing Michiel Borkent
* https://www.youtube.com/watch?v=Nw8aN-nrdEk[Babashka talk at ClojureD]
(https://speakerdeck.com/borkdude/babashka-and-the-small-clojure-interpreter-at-clojured-2020[slides])
by Michiel Borkent
* https://juxt.pro/blog/posts/babashka.html[Babashka: a quick example]
by Malcolm Sparks
* https://stuartsierra.com/2019/12/21/clojure-start-time-in-2019[Clojure
Start Time in 2019] by Stuart Sierra
* https://lambdaisland.com/blog/2019-12-19-advent-of-parens-19-advent-of-random-hacks[Advent
of Random Hacks] by Arne Brasseur
* https://lambdaisland.com/blog/2019-12-05-advent-of-parens-5-clojure-in-the-shell[Clojure
in the Shell] by Arne Brasseur
* https://purelyfunctional.tv/issues/purelyfunctional-tv-newsletter-351-clojure-tool-babashka/[Clojure
Tool] by Eric Normand

== link:doc/build.md[Building babashka]

== link:doc/dev.md[Developing Babashka]

== Including new libraries or classes

Before new libraries or classes go into the standardly distributed
babashka binary, these evaluation criteria are considered:

* The library or class is useful for general purpose scripting.
* Adding the library or class would make babashka more compatible with
Clojure libraries relevant to scripting.
* The library cannot be interpreted by with babashka using
`--classpath`.
* The functionality can't be met by shelling out to another CLI or can't
be written as a small layer over an existing CLI (like `babashka.curl`)
instead.
* The library cannot be implemented a
https://github.com/babashka/babashka.pods[pod].

If not all of the criteria are met, but adding a feature is still useful
to a particular company or niche, adding it behind a feature flag is
still a possibility. This is currently the case for `next.jdbc` and the
`PostgresQL` and `HSQLDB` database drivers. Companies interested in
these features can compile an instance of babashka for their internal
use. Companies are also free to make forks of babashka and include their
own internal libraries. If their customized babashka is interesting to
share with the world, they are free to distribute it using a different
binary name (like `bb-sql`, `bb-docker`, `bb-yourcompany`, etc.). See
the link:doc/build.md#feature-flags[feature flag documentation] and the
implementation of the existing feature flags
(https://github.com/borkdude/babashka/commit/02c7c51ad4b2b1ab9aa95c26a74448b138fe6659[example
commit]).

== Babashka book

In the future we will migrate examples from this README to the babashka
https://book.babashka.org/[book]. This is work in progress and you are
welcome to contribute.

== Related projects

* https://planck-repl.org/[planck]
* https://github.com/candid82/joker[joker]
* https://github.com/dundalek/closh[closh]
* https://github.com/anmonteiro/lumo[lumo]

== Examples

link:examples/README.md[A collection of example scripts].

== Thanks

* https://www.adgoji.com/[adgoji] for financial support
* https://circleci.com/[CircleCI] for CI and additional support
* https://github.com/tonsky[Nikita Prokopov] for the logo
* https://github.com/borkdude/babashka/graphs/contributors[contributors]
and other users posting issues with bug reports and ideas

== Contributors

=== Code Contributors

This project exists thanks to all the people who contribute.
[link:doc/dev.md[Contribute]].

=== Financial Contributors

Become a financial contributor and help us sustain our community.
[https://opencollective.com/babashka/contribute[Contribute]]

==== Individuals

==== Organizations

Support this project with your organization. Your logo will show up here
with a link to your website.
[https://opencollective.com/babashka/contribute[Contribute]]

== License

Copyright © 2019-2020 Michiel Borkent

Distributed under the EPL License. See LICENSE.

This project contains code from:

* Clojure, which is licensed under the same EPL License.
