[[general-usage]]
== General usage

[[command-line-options]]
=== Command line options

Typing `bb --help` from the command line will print all the available command
line options which should give you a sense of the available features in
babashka.

[source,bash]
----
Babashka v0.2.3

Options must appear in the order of groups mentioned below.

Help:

  --help, -h or -?    Print this help text.
  --version           Print the current version of babashka.
  --describe          Print an EDN map with information about this version of babashka.

In- and output flags:

  -i                  Bind *input* to a lazy seq of lines from stdin.
  -I                  Bind *input* to a lazy seq of EDN values from stdin.
  -o                  Write lines to stdout.
  -O                  Write EDN values to stdout.
  --stream            Stream over lines or EDN values from stdin. Combined with -i or -I *input* becomes a single value per iteration.

Uberscript:

  --uberscript <file> Collect preloads, -e, -f and -m and all required namespaces from the classpath into a single executable file.

Evaluation:

  -e, --eval <expr>   Evaluate an expression.
  -f, --file <path>   Evaluate a file.
  -cp, --classpath    Classpath to use.
  -m, --main <ns>     Call the -main function from namespace with args.
  --verbose           Print debug information and entire stacktrace in case of exception.

REPL:

  --repl              Start REPL. Use rlwrap for history.
  --socket-repl       Start socket REPL. Specify port (e.g. 1666) or host and port separated by colon (e.g. 127.0.0.1:1666).
  --nrepl-server      Start nREPL server. Specify port (e.g. 1667) or host and port separated by colon (e.g. 127.0.0.1:1667).

If neither -e, -f, or --socket-repl are specified, then the first argument that is not parsed as a option is treated as a file if it exists, or as an expression otherwise. Everything after that is bound to *command-line-args*. Use -- to separate script command line args from bb command line args.
----

[[running-a-script]]
=== Running a script

Scripts may be executed from a file using `-f` or `--file`:

[source,bash]
----
bb -f download_html.clj
----

Using `bb` with a shebang also works:

[source,clojure]
----
include::example$/usage/download_html.clj[]
----

[source,bash]
----
$ ./download_html.clj
Usage: <url> <file>

$ ./download_html.clj https://www.clojure.org /tmp/clojure.org.html
Fetching url: https://www.clojure.org
Writing file: /tmp/clojure.org.html
----

If `/usr/bin/env` doesn't work for you, you can use the following
workaround:

[source,bash]
----
$ cat script.clj
#!/bin/sh

#_(
   "exec" "bb" "$0" hello "$@"
   )

(prn *command-line-args*)

./script.clj 1 2 3
("hello" "1" "2" "3")
----

=== Current file path

The var `*file*` contains the full path of the file that is currently
being executed:

[source,bash]
----
$ cat example.clj
(prn *file*)

$ bb example.clj
"/Users/borkdude/example.clj"
----

=== Parsing command line arguments

Command-line arguments can be retrieved using `+*command-line-args*+`. If you
want to parse command line arguments, you may use the built-in
`clojure.tools.cli` namespace:


Babashka ships with `clojure.tools.cli`:

[source,clojure]
----
(require '[clojure.tools.cli :refer [parse-opts]])

(def cli-options
  ;; An option with a required argument
  [["-p" "--port PORT" "Port number"
    :default 80
    :parse-fn #(Integer/parseInt %)
    :validate [#(< 0 % 0x10000) "Must be a number between 0 and 65536"]]
   ["-h" "--help"]])

(:options (parse-opts *command-line-args* cli-options))
----

[source,bash]
----
$ bb script.clj
{:port 80}
$ bb script.clj -h
{:port 80, :help true}
----

There is also the
https://github.com/borkdude/babashka/blob/master/doc/projects.md#nubankdocopt[nubank/docopt]
library that is compatible with babashka.

=== System properties

Babashka sets the following system properties:

* `babashka.version`: the version string, e.g. `"1.2.0"`
* `babashka.main`: the `--main` argument
* `babashka.file`: the `--file` argument (normalized using
`.getAbsolutePath`)

In babashka you can read these properties using `System/getProperty`.

=== Data readers

Data readers can be enabled by setting `*data-readers*` to a hashmap of
symbols to functions or vars:

[source,clojure]
----
$ bb "(set! *data-readers* {'t/tag inc}) #t/tag 1"
2
----

To preserve good startup time, babashka does not scan the classpath for
`data_readers.clj` files.

=== Reader conditionals

Babashka supports reader conditionals by taking either the `:bb` or
`:clj` branch, whichever comes first. NOTE: the `:clj` branch behavior
was added in version 0.0.71, before that version the `:clj` branch was
ignored.

[source,clojure]
----
$ bb "#?(:bb :hello :clj :bye)"
:hello

$ bb "#?(:clj :bye :bb :hello)"
:bye

$ bb "[1 2 #?@(:bb [] :clj [1])]"
[1 2]
----
