#!/usr/bin/env bb

(require '[babashka.process :as p]
         '[clojure.string :as str])

(def out-page (str "gh-pages/"
                   (or (System/getenv "BABASHKA_BOOK_MAIN")
                       "master")
                   ".html"))

(spit "src/usage/help.adoc"
      (format "// generated by script/compile.clj\n[source,bash]\n----\n%s\n----\n"
              (-> @(p/$ bb --help)
                  :out
                  slurp
                  str/trim)))

(-> (p/$ asciidoctor src/book.adoc -o ~out-page -a docinfo=shared)
    (p/check))

(binding [*out* *err*]
  (println "Done writing to" out-page))
