#!/usr/bin/env bb

(require '[babashka.fs :as fs]
         '[babashka.process :as p]
         '[clojure.string :as str])

(spit "src/usage/help.adoc"
      (format "// generated by script/compile.clj\n[source,bash]\n----\n%s\n----\n"
              ;; use non-snapshot version
              (-> (p/sh [(if (fs/exists? "/usr/local/bin/bb")
                           "/usr/local/bin/bb"
                           "/opt/homebrew/bin/bb") "--help"])
                  :out
                  str/trim)))
