#!/usr/bin/env bb

(require '[babashka.process :as p]
         '[clojure.string :as str])

(spit "src/usage/help.adoc"
      (format "// generated by script/compile.clj\n[source,bash]\n----\n%s\n----\n"
              ;; use non-snapshot version
              (-> @(p/$ "/usr/local/bin/bb" --help)
                  :out
                  slurp
                  str/trim)))
