[[child_processes]]
== Child processes

There are several ways of creating child processes in babashka. Let's start with
the easiest one.

=== clojure.java.shell

A common way to shell out to another process is via `clojure.java.shell`:

[source,clojure]
----
user=> (require '[clojure.java.shell :refer [sh]])
nil
user=> (sh "ls")
{:exit 0, :out "README.md\ndist\ngh-pages\nscript\nsrc\n", :err ""}
----

As you can see the result of `:out` are the lines of text produced by `ls`. The
`:exit` code was `0` and there was no output on stderr.

[source,clojure]
----
user=> (sh "ls" "foo")
{:exit 1, :out "", :err "ls: foo: No such file or directory\n"}
----

If we invoke `ls` with a non-existing file, there is error output, but not
output on stdout and the `:exit` code is `1`.

For more information on `clojure.java.shell`, read the
https://clojure.github.io/clojure/clojure.java.shell-api.html[API documentation]

=== java.lang.Process

What if we wanted to start a test runner that watches a source directory and
executes tests whenever a file changes? Using `clojure.java.shell/sh` for this
has a few drawbacks:

- We have no control over stopping the watcher process
- We can't see any output from the test runner until the process finishes

Using `java.lang.ProcessBuilder` and `java.lang.Process` gives us the extra
power we need to overcome these limitations.

.test_runner_1.clj
[source,clojure]
----
#!/usr/bin/env bb

(import java.lang.ProcessBuilder$Redirect)

(defn test-runner-watch []
  (let [cmd ["clojure" "-A:kaocha" "-m" "kaocha.runner" "--watch"] <1>
        pb (doto (ProcessBuilder. cmd) <2>
             (.redirectOutput ProcessBuilder$Redirect/INHERIT)) <3>
        proc (.start pb)] <4>
    (-> (Runtime/getRuntime)
        (.addShutdownHook (Thread. #(.destroy proc)))) <5>
    proc))

(.waitFor (test-runner-watch)) <6>
----

<1> The command and its arguments

<2> Construction of a `Process` is done using `ProcessBuilder`

<3> This sends the output of the child process directly to the parent process's
standard out.

<4> Calling `start` on a `ProcessBuilder` instance starts the process and gives
us a `Process` instance.

<5> This line will destroy the child process before the parent process exits.

<6> `waitFor` waits until the child process ends and returns its exit code. If
we would not include this, our script would end without waiting for the watcher.

When calling the script, we can see output from the test runner while it is running:

[source,shell]
----
$ test_runner_watch.clj
[(.................)(..)]
7 tests, 19 assertions, 0 failures.
----

When we change a file in a source directory, the watcher is triggered and the
tests run again.

What if we want to parse the output of the test runner and do something with it?
Instead of sending the output of the child process to stdout we will have to get
a hold of it. This is possible via https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Process.html#getInputStream()[`getInputStream`].


.test_runner_2.clj
[source,clojure]
----
include::test_runner_2.clj[]
----

<1> We ask the test runner not to output ANSI color codes which makes parsing
the output easier

<2> Instead of forwarding the output of the child process to stdout we now grab
it as a `java.lang.InputStream`

<3> The function `process-line` parses a line of output of the test runner and returns it as EDN data

<4> The function `stderr` prints the line to stderr and returns it.

<5> The function `watch` starts the test-runner in watch mode and applies the
`callback` function on succesfully parsed lines

<6> Finally we call the `watch` function with `prn` as the callback function.

Running this script prints EDN data to stdout and the rest of the output goes to stderr:

[source,shell]
----
[(.................)(..)]
7 tests, 19 assertions, 0 failures.
{:errors 0, :failures 0, :tests 7, :assertions 19}
----

A more interesting callback could be one that calls a notifier like https://github.com/tonsky/AnyBar[AnyBar] or https://github.com/limpbrains/somebar[somebar]:

.test_runner_3.clj
[source,clojure]
----
include::test_runner_3.clj[lines=47..]
----

<1> `1738` is the default AnyBar UDP port
<2> In case of failures or errors we set AnyBar to red, else to green.

In some scripts it might be desirable to set the working directory and
environment variables of the child process. Also it might be the last step in a
script and you just want to let it run until it finishes:

.test_runner_4.clj
[source,clojure]
----
include::test_runner_4.clj[]
----

<1> We interpret the first command line arg as the working directory for the test runner

<2> Remaining args are passed through to the test runner

<3> https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ProcessBuilder.html#inheritIO()[`.inheritIO`] is a convenience method. According to its documentation: Sets the source and destination for subprocess
standard I/O to be the same as those of the current Java process.

<4> Here we set the child process' environment variable `CI` to `false`

<5> We wait for the process to end and exit with its exit code.

[source,shell]
----
$ test_runner_4.clj ~/projects/carve --watch
[(.................)(..)]
7 tests, 19 assertions, 0 failures.
----
