[[child_processes]]
== Child processes

There are several ways of creating child processes in babashka. Let's start with
the easiest one.

=== clojure.java.shell

A common way to shell out to another process is via `clojure.java.shell`:

[source,clojure]
----
user=> (require '[clojure.java.shell :refer [sh]])
nil
user=> (sh "ls")
{:exit 0, :out "README.md\ndist\ngh-pages\nscript\nsrc\n", :err ""}
----

As you can see the result of `:out` are the lines of text produced by `ls`. The
`:exit` code was `0` and there was no output on stderr.

[source,clojure]
----
user=> (sh "ls" "foo")
{:exit 1, :out "", :err "ls: foo: No such file or directory\n"}
----

If we invoke `ls` with a non-existing file, there is error output, but not
output on stdout and the `:exit` code is `1`.

For more information on `clojure.java.shell`, read the
https://clojure.github.io/clojure/clojure.java.shell-api.html[API documentation]

=== java.lang.Process

What if we wanted to start a test runner that watches a source directory and
executes tests whenever a file changes? Using `clojure.java.shell/sh` for this
has a few drawbacks:

- We have no control over stopping the watcher process
- We can't see any output from the test runner until the process finishes

Using `java.lang.ProcessBuilder` and `java.lang.Process` gives us the extra
power we need to overcome these limitations.

[source,clojure]
----
#!/usr/bin/env bb

(defn test-runner-watch []
  (let [cmd ["clojure" "-A:kaocha" "-m" "kaocha.runner" "--watch"]
        pb (doto (ProcessBuilder. cmd)
             (.inheritIO))
        proc (.start pb)]
    (-> (Runtime/getRuntime)
        (.addShutdownHook (Thread. #(.destroy proc))))
    proc))

(.waitFor (test-runner-watch))
----
