[[differences-with-clojure]]
== Differences with Clojure

Babashka is implemented using the https://github.com/borkdude/sci[Small
Clojure Interpreter]. This means that a snippet or script is not
compiled to JVM bytecode, but executed form by form by a runtime which
implements a substantial subset of Clojure. Babashka is compiled to a
native binary using https://github.com/oracle/graal[GraalVM]. It comes
with a selection of built-in namespaces and functions from Clojure and
other useful libraries. The data types (numbers, strings, persistent
collections) are the same. Multi-threading is supported (`pmap`,
`future`).

Differences with Clojure:

* A pre-selected set of Java classes are supported. You cannot add Java
classes at runtime.
* Interpretation comes with overhead. Therefore loops are slower than in
Clojure on the JVM. In general interpretation yields slower programs
than compiled programs.
* `deftype` support is limited to protocols, `Object` and `IPersistentMap`.
* `definterface` is not supported
* `defprotocol` and `defrecord` are implemented using multimethods and
regular maps. Ostensibly they work the same, but under the hood there
are no Java classes that correspond to them. Do not depend on this implementation detail since it may change in future version of babashka.
* Currently `reify` works only for one class at a time
