[[features]]
// why do I need a new line here to make TOC work properly?

== Features

Typing `bb --help` from the command line will print all the available command
line options which should give you a sense of the available features in
babashka.

[source,bash]
----
Babashka v0.2.3

Options must appear in the order of groups mentioned below.

Help:

  --help, -h or -?    Print this help text.
  --version           Print the current version of babashka.
  --describe          Print an EDN map with information about this version of babashka.

In- and output flags:

  -i                  Bind *input* to a lazy seq of lines from stdin.
  -I                  Bind *input* to a lazy seq of EDN values from stdin.
  -o                  Write lines to stdout.
  -O                  Write EDN values to stdout.
  --stream            Stream over lines or EDN values from stdin. Combined with -i or -I *input* becomes a single value per iteration.

Uberscript:

  --uberscript <file> Collect preloads, -e, -f and -m and all required namespaces from the classpath into a single executable file.

Evaluation:

  -e, --eval <expr>   Evaluate an expression.
  -f, --file <path>   Evaluate a file.
  -cp, --classpath    Classpath to use.
  -m, --main <ns>     Call the -main function from namespace with args.
  --verbose           Print debug information and entire stacktrace in case of exception.

REPL:

  --repl              Start REPL. Use rlwrap for history.
  --socket-repl       Start socket REPL. Specify port (e.g. 1666) or host and port separated by colon (e.g. 127.0.0.1:1666).
  --nrepl-server      Start nREPL server. Specify port (e.g. 1667) or host and port separated by colon (e.g. 127.0.0.1:1667).

If neither -e, -f, or --socket-repl are specified, then the first argument that is not parsed as a option is treated as a file if it exists, or as an expression otherwise. Everything after that is bound to *command-line-args*. Use -- to separate script command line args from bb command line args.
----

=== Built-in namespaces

In addition to `clojure.core`, the following namespaces are available in babashka.
Some are available through pre-defined aliases in the `user` namespace,
which can be handy for one-liners. If not all vars are available, they
are enumerated explicitly. If some important var is missing, an issue or
PR is welcome.

From Clojure:

* `clojure.core`
* `clojure.core.protocols`: `Datafiable`, `Navigable`
* `clojure.data`
* `clojure.datafy`
* `clojure.edn` aliased as `edn`
* `clojure.java.browse`
* `clojure.java.io` aliased as `io`:
** `as-relative-path`, `as-url`, `copy`, `delete-file`, `file`,
`input-stream`, `make-parents`, `output-stream`, `reader`, `resource`,
`writer`
* `clojure.java.shell` aliased as `shell`
* `clojure.main`: `demunge`, `repl`, `repl-requires`
* `clojure.pprint`: `pprint`, `cl-format`
* `clojure.set` aliased as `set`
* `clojure.string` aliased as `str`
* `clojure.stacktrace`
* `clojure.test`
* `clojure.zip`

Additional libraries:

* https://github.com/borkdude/babashka.curl[`babashka.curl`]
* https://github.com/babashka/process[`babashka/process`]
* https://github.com/nrepl/bencode[`bencode.core`] aliased as `bencode`:
`read-bencode`, `write-bencode`
* https://github.com/dakrone/cheshire[`cheshire.core`] aliased as `json`
* https://clojure.github.io/core.async/[`clojure.core.async`] aliased as
`async`. Also see https://github.com/borkdude/babashka#coreasync[docs].
* https://github.com/clojure/data.csv[`clojure.data.csv`] aliased as
`csv`
* https://github.com/clojure/data.xml[`clojure.data.xml`] aliased as
`xml`
* https://github.com/clojure/tools.cli[`clojure.tools.cli`] aliased as
`tools.cli`
* https://github.com/clj-commons/clj-yaml[`clj-yaml.core`] alias as
`yaml`
* https://github.com/cognitect/transit-clj[`cognitect.transit`] aliased
as `transit`
* https://github.com/http-kit/http-kit[`org.httpkit.client`]
* https://github.com/http-kit/http-kit[`org.httpkit.server`]

See the
https://github.com/borkdude/babashka/blob/master/doc/projects.md[projects]
page for libraries that are not built-in, but which you can load from
source via the `--classpath` option.

See the
https://github.com/borkdude/babashka/blob/master/doc/build.md[build]
page for built-in libraries that can be enabled via feature flags, if
you want to compile babashka yourself.

A selection of Java classes are available, see
`babashka/impl/classes.clj` in babashka's git repo.

=== Babashka namespaces

[[babashka_classpath]]
==== babashka.classpath

Contains the function `add-classpath` which can be used to add to the
classpath dynamically:

[source,clojure]
----
(require '[babashka.classpath :refer [add-classpath]]
         '[clojure.java.shell :refer [sh]]
         '[clojure.string :as str])

(def medley-dep '{:deps {medley {:git/url "https://github.com/borkdude/medley"
                                 :sha "91adfb5da33f8d23f75f0894da1defe567a625c0"}}})
(def cp (-> (sh "clojure" "-Spath" "-Sdeps" (str medley-dep)) :out str/trim))
(add-classpath cp)
(require '[medley.core :as m])
(m/index-by :id [{:id 1} {:id 2}]) ;;=> {1 {:id 1}, 2 {:id 2}}
----

[[babashkawait]]
==== babashka.wait

Contains the functions: `wait-for-port` and `wait-for-path`.

Usage of `wait-for-port`:

[source,clojure]
----
(wait/wait-for-port "localhost" 8080)
(wait/wait-for-port "localhost" 8080 {:timeout 1000 :pause 1000})
----

Waits for TCP connection to be available on host and port. Options map
supports `:timeout` and `:pause`. If `:timeout` is provided and reached,
`:default`'s value (if any) is returned. The `:pause` option determines
the time waited between retries.

Usage of `wait-for-path`:

[source,clojure]
----
(wait/wait-for-path "/tmp/wait-path-test")
(wait/wait-for-path "/tmp/wait-path-test" {:timeout 1000 :pause 1000})
----

Waits for file path to be available. Options map supports `:default`,
`:timeout` and `:pause`. If `:timeout` is provided and reached,
`:default`'s value (if any) is returned. The `:pause` option determines
the time waited between retries.

The namespace `babashka.wait` is aliased as `wait` in the `user`
namespace.

[[babashkasignal]]
==== babashka.signal

Contains the function `signal/pipe-signal-received?`. Usage:

[source,clojure]
----
(signal/pipe-signal-received?)
----

Returns true if `PIPE` signal was received. Example:

[source,bash]
----
$ bb '((fn [x] (println x) (when (not (signal/pipe-signal-received?)) (recur (inc x)))) 0)' | head -n2
1
2
----

The namespace `babashka.signal` is aliased as `signal` in the `user`
namespace.

[[babashkacurl]]
==== babashka.curl

The namespace `babashka.curl` is a tiny wrapper around curl. It's aliased as
`curl` in the user namespace. See
https://github.com/borkdude/babashka.curl[babashka.curl] for how to use it.

[[babashkaprocess]]
==== babashka.process

The `babashka.process` process library. See the
https://github.com/babashka/process[process] repo for API docs.
