[[introduction]]
== Introduction

Welcome reader! This is a book about scripting with Clojure and babashka.
https://www.clojure.org[Clojure] is a functional, dynamic programming language from the Lisp family which runs on the JVM. Babashka is a scripting environment made with Clojure, compiled to native with https://www.graalvm.org[GraalVM]. The primary benefits of using babashka for scripting compared to the JVM are fast startup time and low memory consumption. Babashka comes with batteries included and packs libraries like `clojure.tools.cli` for parsing command line arguments and `cheshire` for working with JSON. Moreover, it can be installed just by downloading a self-contained binary.

=== Target audience

Babashka is written for developers who are familiar with Clojure on the JVM. This book assumes familiarity with Clojure and is not a Clojure tutorial. If you aren't that familiar with Clojure but you're curious to learn, check out https://gist.github.com/yogthos/be323be0361c589570a6da4ccc85f58f[this] list of beginner resources.

=== Compatibility

Babashka uses the Small Clojure Interpreter, or https://github.com/borkdude/sci/[sci] for short to run programs within a GraalVM-compiled binary. GraalVM gives it it's fast startup and low memory usage characteristics. Source code is not compiled to JVM-byte code first, like in Clojure on the JVM. Despite this difference, babashka aims to be as compatible as possible with the semantics of Clojure. It supports a sufficiently large subset of Clojure: functions, macros, multi-methods, namespaces, most of it is there. At the moment, the main difference with Clojure is lack of support for `defrecord`, `defprotocol` and `reify`. Like a JVM programmer would expect, babashka has support for multi-threading and provides access to commonly used Java packages and classes like `File`, `System`, `java.io` and `java.net`. Because babashka uses interpretation instead of compilation, some longer running programs may be slower, despite the benefit of fast startup. If that turns out to be the case, your efforts are not in vain: the code you wrote still runs with Clojure!
