[[libraries]]
// why do I need a new line here to make TOC work properly?

== Libraries

[[built-in-namespaces]]
=== Built-in namespaces

In addition to `clojure.core`, the following libraries / namespaces are available in babashka.
Some are available through pre-defined aliases in the `user` namespace,
which can be handy for one-liners. If not all vars are available, they
are enumerated explicitly. If some important var is missing, an issue or
PR is welcome.

From Clojure:

* `clojure.core`
* `clojure.core.protocols`: `Datafiable`, `Navigable`
* `clojure.data`
* `clojure.datafy`
* `clojure.edn` aliased as `edn`
* `clojure.math`
* `clojure.java.browse`
* `clojure.java.io` aliased as `io`:
** `as-relative-path`, `as-url`, `copy`, `delete-file`, `file`,
`input-stream`, `make-parents`, `output-stream`, `reader`, `resource`,
`writer`
* `clojure.java.shell` aliased as `shell`
* `clojure.main`: `demunge`, `repl`, `repl-requires`
* `clojure.pprint`: `pprint`, `cl-format`
* `clojure.set` aliased as `set`
* `clojure.string` aliased as `str`
* `clojure.stacktrace`
* `clojure.test`
* `clojure.walk`
* `clojure.zip`

Additional libraries:

* https://github.com/babashka/cli[`babashka.cli`]: CLI arg parsing
* https://github.com/babashka/http-client[`babashka.http-client`]: making HTTP requests
* https://github.com/babashka/process[`babashka.process`]: shelling out to external processes
* https://github.com/babashka/fs[`babashka.fs`]: file system manipulation
* https://github.com/nrepl/bencode[`bencode.core`] aliased as `bencode`:
`read-bencode`, `write-bencode`
* https://github.com/dakrone/cheshire[`cheshire.core`] aliased as `json`: dealing with JSON
* https://clojure.github.io/core.async/[`clojure.core.async`] aliased as
`async`.
* https://github.com/clojure/data.csv[`clojure.data.csv`] aliased as
`csv`
* https://github.com/clojure/data.xml[`clojure.data.xml`] aliased as
`xml`
* https://github.com/clojure/tools.cli[`clojure.tools.cli`] aliased as
`tools.cli`
* https://github.com/clj-commons/clj-yaml[`clj-yaml.core`] alias as
`yaml`
* https://github.com/cognitect/transit-clj[`cognitect.transit`] aliased
as `transit`
* https://github.com/http-kit/http-kit[`org.httpkit.client`]
* https://github.com/http-kit/http-kit[`org.httpkit.server`]
* https://github.com/clojure/core.match[`clojure.core.match`]
* https://github.com/weavejester/hiccup/[`hiccup.core`] and `hiccup2.core`
* https://github.com/clojure/test.check[`clojure.test.check`]:
  - `clojure.test.check`
  - `clojure.test.check.generators`
  - `clojure.test.check.properties`
* https://github.com/clj-commons/rewrite-clj[`rewrite-clj`]:
 - `rewrite-clj.parser`
 - `rewrite-clj.node`
 - `rewrite-clj.zip`
 - `rewrite-clj.paredit`
* https://github.com/yogthos/Selmer[`Selmer`]:
 - `selmer.parser`
* https://github.com/clojure/tools.logging[`clojure.tools.logging`]
* https://github.com/ptaoussanis/timbre[`taoensso.timbre`]: logging
* https://github.com/borkdude/edamame[`edamame.core`]: Clojure parser
* https://github.com/clojure/core.rrb-vector[`core.rrb-vector`]
* https://github.com/nextjournal/markdown[`nextjournal.markdown`]
* https://github.com/jhy/jsoup[`Jsoup`]
* https://github.com/jline/jline3[`JLine`]: terminal input handling

TIP:  Is your library built into babashka? +
<<badges, Add the babashka built-in badge >> to let the babashka community know! +
{badge-built-in}

Check out the https://babashka.org/toolbox/[babashka toolbox] and
https://github.com/borkdude/babashka/blob/master/doc/projects.md[projects] page
for libraries that are not built-in, but which you can load as an external
dependency in https://book.babashka.org/#_bb_edn[`bb.edn`].

See the
https://github.com/borkdude/babashka/blob/master/doc/build.md[build]
page for built-in libraries that can be enabled via feature flags, if
you want to compile babashka yourself.

A selection of Java classes are available, see
https://github.com/babashka/babashka/blob/master/src/babashka/impl/classes.clj[`babashka/impl/classes.clj`]
in babashka's git repo.

=== Babashka namespaces

[[babashka_classpath]]
==== babashka.classpath

Available functions:

- `add-classpath`
- `get-classpath`
- `split-classpath`

===== add-classpath

The function `add-classpath` which can be used to add to the classpath
dynamically:

[source,clojure]
----
(require '[babashka.classpath :refer [add-classpath]]
         '[clojure.java.shell :refer [sh]]
         '[clojure.string :as str])

(def medley-dep '{:deps {medley {:git/url "https://github.com/borkdude/medley"
                                 :sha "91adfb5da33f8d23f75f0894da1defe567a625c0"}}})
(def cp (-> (sh "clojure" "-Spath" "-Sdeps" (str medley-dep)) :out str/trim))
(add-classpath cp)
(require '[medley.core :as m])
(m/index-by :id [{:id 1} {:id 2}]) ;;=> {1 {:id 1}, 2 {:id 2}}
----

===== get-classpath

The function `get-classpath` returns the classpath as set by `--classpath`,
`BABASHKA_CLASSPATH` and `add-classpath`.

===== split-classpath

Given a classpath, returns a seq of strings as the result of splitting the
classpath by the platform specific path separatator.

[[babashkadeps]]
==== babashka.deps

Available functions:

- `add-deps`
- `clojure`
- `merge-deps`

===== add-deps

The function `add-deps` takes a deps edn map like `{:deps {medley/medley
{:mvn/version "1.3.0"}}}`, resolves it using
https://github.com/borkdude/deps.clj[deps.clj] and then adds to the babashka
classpath accordingly.

Example:

[source,clojure]
----
(require '[babashka.deps :as deps])

(deps/add-deps '{:deps {medley/medley {:mvn/version "1.3.0"}}})

(require '[medley.core :as m])
(m/index-by :id [{:id 1} {:id 2}])
----

Optionally, `add-deps` takes a second arg with options. Currently the only
option is `:aliases` which will affect how deps are resolved:

Example:

[source,clojure]
----
(deps/add-deps '{:aliases {:medley {:extra-deps {medley/medley {:mvn/version "1.3.0"}}}}}
               {:aliases [:medley]})
----

===== clojure

The function `clojure` takes a sequential collection of arguments, similar to
the clojure CLI. The arguments are then passed to
https://github.com/borkdude/deps.clj[deps.clj]. The `clojure` function returns
`nil` and prints to `*out*` for commands like `-Stree`, and `-Spath`. For `-M`,
`-X` and `-A` it invokes `java` with `babashka.process/process` (see
link:#babashkaprocess[babashka.process]) and returns the associated record. For
more details, read the docstring with:

[source,clojure]
----
(require '[clojure.repl :refer [doc]])
(doc babashka.deps/clojure)
----

Example:

The following script passes through command line arguments to clojure, while
adding the medley dependency:

[source,clojure]
----
(require '[babashka.deps :as deps])

(def deps '{:deps {medley/medley {:mvn/version "1.3.0"}}})
(def clojure-args (list* "-Sdeps" deps  *command-line-args*))

(if-let [proc (deps/clojure clojure-args)]
  (-> @proc :exit (System/exit))
  (System/exit 0))
----

[[babashkawait]]
==== babashka.wait

Contains the functions: `wait-for-port` and `wait-for-path`.

Usage of `wait-for-port`:

[source,clojure]
----
(wait/wait-for-port "localhost" 8080)
(wait/wait-for-port "localhost" 8080 {:timeout 1000 :pause 1000})
----

Waits for TCP connection to be available on host and port. Options map
supports `:timeout` and `:pause`. If `:timeout` is provided and reached,
`:default`'s value (if any) is returned. The `:pause` option determines
the time waited between retries.

Usage of `wait-for-path`:

[source,clojure]
----
(wait/wait-for-path "/tmp/wait-path-test")
(wait/wait-for-path "/tmp/wait-path-test" {:timeout 1000 :pause 1000})
----

Waits for file path to be available. Options map supports `:default`,
`:timeout` and `:pause`. If `:timeout` is provided and reached,
`:default`'s value (if any) is returned. The `:pause` option determines
the time waited between retries.

The namespace `babashka.wait` is aliased as `wait` in the `user`
namespace.

[[babashkasignal]]
==== babashka.signal

Contains the function `signal/pipe-signal-received?`. Usage:

[source,clojure]
----
(signal/pipe-signal-received?)
----

Returns true if `PIPE` signal was received. Example:

[source,bash]
----
$ bb -e '((fn [x] (println x) (when (not (signal/pipe-signal-received?)) (recur (inc x)))) 0)' | head -n2
1
2
----

The namespace `babashka.signal` is aliased as `signal` in the `user`
namespace.

[[babashkahttpclient]]
==== babashka.http-client

The `babashka.http-client` library for making HTTP requests. See
https://github.com/babashka/http-client[babashka.http-client] for how to use it.

[[babashkaprocess]]
==== babashka.process

The `babashka.process` library. See the
https://github.com/babashka/process[process] repo for API docs.

[[babashkafs]]
==== babashka.fs

The `babashka.fs` library offers file system utilities. See the
https://github.com/babashka/fs[fs] repo for API docs.

[[babashkacli]]
==== babashka.cli

The `babashka.cli` library allows you to turn functions into CLIs. See the
https://github.com/babashka/cli[cli] repo for API docs and check out the
https://book.babashka.org/#_babashka_cli[babashka CLI] chapter on how to use it
from the command line or with https://book.babashka.org/#tasks[tasks].

[[projects]]
=== Projects

Babashka is able to run Clojure projects from source, if they are compatible
with the subset of Clojure that sci is capable of running.

Check this
https://github.com/borkdude/babashka/blob/master/doc/projects.md[page] for
projects that are known to work with babashka.

TIP: Is your library compatible with babashka? +
<<badges, Add the babashka compatible badge>>, the babashka community will appreciate it! +
{badge-compatible}
