[[usage]]
== Usage

Typing `bb help` from the command line will print all the available command
line options which should give you a sense of the available features in
babashka.

[source,bash]
----
Babashka v0.3.1

Usage: bb [classpath opts] [eval opts] [cmdline args]
or:    bb [classpath opts] file [cmdline args]
or:    bb [classpath opts] subcommand [subcommand opts] [cmdline args]

Classpath:

  -cp, --classpath     Classpath to use. Overrides bb.edn classpath.

Evaluation:

  -e, --eval <expr>    Evaluate an expression.
  -f, --file <path>    Evaluate a file.
  -m, --main <ns|var>  Call the -main function from a namespace or call a fully qualified var.
  --verbose            Print debug information and entire stacktrace in case of exception.

Help:

  help, -h or -?     Print this help text.
  version            Print the current version of babashka.
  describe           Print an EDN map with information about this version of babashka.
  doc <var|ns>       Print docstring of var or namespace. Requires namespace if necessary.

REPL:

  repl                 Start REPL. Use rlwrap for history.
  socket-repl  [addr]  Start a socket REPL. Addr opt defaults to localhost:1666.
  nrepl-server [addr]  Start nREPL server. Address option defaults to locahost:1667.

Clojure:

  clojure [args...]  Invokes clojure. Takes same args as the official clojure CLI.

Packaging:

  uberscript <file> [eval-opt]  Collect all required namespaces from the classpath into a single file. Accepts additional eval opts, like `-m`.
  uberjar    <jar>  [eval-opt]  Similar to uberscript but creates jar file.

In- and output flags (only to be used with -e one-liners):

  -i                 Bind *input* to a lazy seq of lines from stdin.
  -I                 Bind *input* to a lazy seq of EDN values from stdin.
  -o                 Write lines to stdout.
  -O                 Write EDN values to stdout.
  --stream           Stream over lines or EDN values from stdin. Combined with -i or -I *input* becomes a single value per iteration.

File names take precedence over subcommand names.
Remaining arguments are bound to *command-line-args*.
Use -- to separate script command line args from bb command line args.
When no eval opts or subcommand is provided, the implicit subcommand is repl.
----

=== Running a script

Scripts may be executed from a file using `-f` or `--file`:

[source,bash]
----
bb -f download_html.clj
----

The file may also be passed directly, without `-f`:

[source,bash]
----
bb download_html.clj
----

Using `bb` with a shebang also works:

[source,clojure]
----
include::usage/download_html.clj[]
----

[source,bash]
----
$ ./download_html.clj
Usage: <url> <file>

$ ./download_html.clj https://www.clojure.org /tmp/clojure.org.html
Downloading url: https://www.clojure.org
Writing file: /tmp/clojure.org.html
----

If `/usr/bin/env` doesn't work for you, you can use the following
workaround:

[source,bash]
----
$ cat script.clj
#!/bin/sh

#_(
   "exec" "bb" "$0" hello "$@"
   )

(prn *command-line-args*)

./script.clj 1 2 3
("hello" "1" "2" "3")
----

=== Current file path

The var `*file*` contains the full path of the file that is currently
being executed:

[source,bash]
----
$ cat example.clj
(prn *file*)

$ bb example.clj
"/Users/borkdude/example.clj"
----

=== Parsing command line arguments

Command-line arguments can be retrieved using `*command-line-args*`. If you
want to parse command line arguments, you may use the built-in
`clojure.tools.cli` namespace:


Babashka ships with `clojure.tools.cli`:

[source,clojure]
----
(require '[clojure.tools.cli :refer [parse-opts]])

(def cli-options
  ;; An option with a required argument
  [["-p" "--port PORT" "Port number"
    :default 80
    :parse-fn #(Integer/parseInt %)
    :validate [#(< 0 % 0x10000) "Must be a number between 0 and 65536"]]
   ["-h" "--help"]])

(:options (parse-opts *command-line-args* cli-options))
----

[source,bash]
----
$ bb script.clj
{:port 80}
$ bb script.clj -h
{:port 80, :help true}
----

There is also the
https://github.com/borkdude/babashka/blob/master/doc/projects.md#nubankdocopt[nubank/docopt]
library that is compatible with babashka.

=== Project setup

==== Classpath

When you want to organize babashka scripts like a regular Clojure project, you
will need to set a classpath.

Babashka accepts a `--classpath` option that will be used to search for
namespaces when requiring them. Say we have a file `src/my/namespace.clj`:

[source,clojure]
----
(ns my.namespace)
(defn -main [& args]
  (apply println "Hello from my namespace!" args))
----

Now we can execute this main function with:

[source,clojure]
----
$ bb --classpath src --main my.namespace 1 2 3
Hello from my namespace! 1 2 3
----

If you have a larger script with a classic Clojure project layout like

[source,bash]
----
$ tree -L 3
├── deps.edn
├── README
├── src
│   └── project_namespace
│       ├── main.clj
│       └── utilities.clj
└── test
    └── project_namespace
        ├── test_main.clj
        └── test_utilities.clj
----

then you can tell babashka to include both the `src` and `test` folders
in the classpath and start a socket REPL by running:

[source,bash]
----
$ bb --classpath src:test socket-repl 1666
----

If there is no `--classpath` argument, the `BABASHKA_CLASSPATH` environment
variable will be used.

Also see the link:#babashka_classpath[babashka.classpath]
namespace which allows dynamically adding to the classpath.

The namespace link:#babashkadeps[babashka.deps] integrates
https://github.com/clojure/tools.deps.alpha[tools.deps] with babashka and allows
you to set the classpath using a `deps.edn` map.

==== bb.edn

Since version 0.3.1, babashka supports a local `bb.edn` file where you can declare one
or multiple paths and dependencies so they are automatically added to the classpath:

[source,clojure]
----
{:paths ["src"]
 :deps {medley/medley {:mvn/version "1.3.0"}}}
----

[source,clojure]
----
$ bb -e "(require '[medley.core :as m]) (m/index-by :id [{:id 1} {:id 2}])"
{1 {:id 1}, 2 {:id 2}}
----

===== :min-bb-version

Since version 0.3.6, babashka supports the `:min-bb-version` where the minimal
babashka version can be declared:

[source,clojure]
----
{:paths ["src"]
 :deps {medley/medley {:mvn/version "1.3.0"}}
 :min-bb-version "1.0.0"}
----

When using an older bb version (that supports `:min-bb-version`), babashka will
print a warning:

[source]
---
WARNING: this project requires babashka 1.0.0 or newer, but you have: 0.3.6
---
[source]

==== Invoking a main function

A main function can be invoked with `-m` or `--main` like shown above. When
given the argument `foo.bar`, the namespace `foo.bar` will be required and the
function `foo.bar/-main` will be called with command line arguments as strings.

Since babashka 0.3.1 you may pass a fully qualified symbol to `-m`:

[source,clojure]
----
$ bb -m clojure.core/prn 1 2 3
"1" "2" "3"
----

so you can execute any function as a main function, as long as it accepts
varargs arguments.

When invoking `bb` with a main function, the expression `(System/getProperty
"babashka.main")` will return the name of the main function.

=== Preloads

The environment variable `BABASHKA_PRELOADS` allows to define code that
will be available in all subsequent usages of babashka.

[source,bash]
----
BABASHKA_PRELOADS='(defn foo [x] (+ x 2))'
BABASHKA_PRELOADS=$BABASHKA_PRELOADS' (defn bar [x] (* x 2))'
export BABASHKA_PRELOADS
----

Note that you can concatenate multiple expressions. Now you can use
these functions in babashka:

[source,bash]
----
$ bb '(-> (foo *input*) bar)' <<< 1
6
----

You can also preload an entire file using `load-file`:

[source,bash]
----
export BABASHKA_PRELOADS='(load-file "my_awesome_prelude.clj")'
----

Note that `*input*` is not available in preloads.

include::usage/repl.adoc[]

include::usage/io-flags.adoc[]

=== Uberscript

The `--uberscript` option collects the expressions in
`BABASHKA_PRELOADS`, the command line expression or file, the main
entrypoint and all required namespaces from the classpath into a single
file. This can be convenient for debugging and deployment.

Here is an example that uses a function from the
https://github.com/clj-commons/fs[clj-commons/fs] library.

Let's first set the classpath:

[source,clojure]
----
$ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {clj-commons/fs {:mvn/version "1.6.307"}}}')
----

Write a little script, say `glob.clj`:

[source,clojure]
----
(ns glob (:require [me.raynes.fs :as fs]))

(run! (comp println str)
      (fs/glob (first *command-line-args*)))
----

For testing, we'll make a file which we will find using the glob function:

[source,bash]
----
$ touch README.md
----

Now we can execute the script which uses the library:

[source,bash]
----
$ time bb glob.clj '*.md'
/private/tmp/glob/README.md
bb glob.clj '*.md'   0.03s  user 0.01s system 88% cpu 0.047 total
----

Producing an uberscript with all required code:

[source,bash]
----
$ bb uberscript glob-uberscript.clj -f glob.clj
----

To prove that we don't need the classpath anymore:

[source,bash]
----
$ unset BABASHKA_CLASSPATH
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.03s  user 0.02s system 93% cpu 0.049 total
----

Caveats:

* _Dynamic requires_. Building uberscripts works by running top-level
`ns` and `require` forms. The rest of the code is not evaluated. Code
that relies on dynamic requires may not work in an uberscript.
* _Resources_. The usage of `io/resource` assumes a classpath, so when
this is used in your uberscript, you still have to set a classpath and
bring the resources along.

If any of the above is problematic for your project, using an
link:#uberjar[uberjar] is a good alternative.

==== Carve

Uberscripts can be optimized by cutting out unused vars with
https://github.com/borkdude/carve[carve].

[source,bash]
----
$ wc -l glob-uberscript.clj
     583 glob-uberscript.clj
$ carve --opts '{:paths ["glob-uberscript.clj"] :aggressive true :silent true}'
$ wc -l glob-uberscript.clj
     105 glob-uberscript.clj
----

Note that the uberscript became 72% shorter. This has a beneficial
effect on execution time:

[source,bash]
----
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.02s  user 0.01s system 84% cpu 0.034 total
----

=== Uberjar

Babashka can create uberjars from a given classpath and optionally a
main method:

[source,clojure]
----
$ cat src/foo.clj
(ns foo (:gen-class)) (defn -main [& args] (prn :hello))
$ bb -cp $(clojure -Spath) uberjar foo.jar -m foo
$ bb foo.jar
:hello
----

When producing a classpath using the `clojure` or `deps.clj` tool,
Clojure itself, spec and the core specs will be on the classpath and
will therefore be included in your uberjar, which makes it bigger than
necessary:

[source,bash]
----
$ ls -lh foo.jar
-rw-r--r--  1 borkdude  staff   4.5M Aug 19 17:04 foo.jar
----

To exclude these dependencies, you can use the following
`:classpath-overrides` in your `deps.edn`:

[source,clojure]
----
{:aliases {:remove-clojure {:classpath-overrides {org.clojure/clojure nil
                                                  org.clojure/spec.alpha nil
                                                  org.clojure/core.specs.alpha nil}}}}
----

[source,clojure]
----
$ rm foo.jar
$ bb -cp $(clojure -A:remove-clojure -Spath) uberjar foo.jar -m foo
$ bb foo.jar
:hello
$ ls -lh foo.jar
-rw-r--r--  1 borkdude  staff   871B Aug 19 17:07 foo.jar
----

If you want your uberjar to be compatible with the JVM, you'll need to
compile the main namespace. Babashka does not do compilation, so we use
Clojure on the JVM for that part:

[source,clojure]
----
$ rm foo.jar
$ mkdir classes
$ clojure -e "(require 'foo) (compile 'foo)"
foo
$ bb -cp $(clojure -Spath):classes uberjar foo.jar -m foo
$ bb foo.jar
:hello
$ java -jar foo.jar
:hello
----

=== System properties

Babashka sets the following system properties:

* `babashka.version`: the version string, e.g. `"1.2.0"`
* `babashka.main`: the `--main` argument
* `babashka.file`: the `--file` argument (normalized using
`.getAbsolutePath`)

=== Data readers

Data readers can be enabled by setting `*data-readers*` to a hashmap of
symbols to functions or vars:

[source,clojure]
----
$ bb -e "(set! *data-readers* {'t/tag inc}) #t/tag 1"
2
----

To preserve good startup time, babashka does not scan the classpath for
`data_readers.clj` files.

=== Reader conditionals

Babashka supports reader conditionals by taking either the `:bb` or
`:clj` branch, whichever comes first. NOTE: the `:clj` branch behavior
was added in version 0.0.71, before that version the `:clj` branch was
ignored.

[source,clojure]
----
$ bb -e "#?(:bb :hello :clj :bye)"
:hello

$ bb -e "#?(:clj :bye :bb :hello)"
:bye

$ bb -e "[1 2 #?@(:bb [] :clj [1])]"
[1 2]
----

=== Invoking clojure

Babashka bundles https://github.com/borkdude/deps.clj[deps.clj] for invoking a
`clojure` JVM process:

[source,clojure]
----
$ bb clojure -M -e "*clojure-version*"
{:major 1, :minor 10, :incremental 1, :qualifier nil}
----

See the link:#_clojure[clojure] function in the
link:#babashkadeps[babashka.deps] namespace for programmatically invoking
clojure.
