[[usage]]
== Usage

Typing `bb help` from the command line will print all the available command
line options which should give you a sense of the available features in
babashka.

include::usage/help.adoc[]

=== Running a script

Scripts may be executed from a file using `-f` or `--file`:

[source,bash]
----
bb -f download_html.clj
----

The file may also be passed directly, without `-f`:

[source,bash]
----
bb download_html.clj
----

Using `bb` with a shebang also works:

[source,clojure]
----
include::usage/download_html.clj[]
----

[source,bash]
----
$ ./download_html.clj
Usage: <url> <file>

$ ./download_html.clj https://www.clojure.org /tmp/clojure.org.html
Downloading url: https://www.clojure.org
Writing file: /tmp/clojure.org.html
----

If `/usr/bin/env` doesn't work for you, you can use the following
workaround:

[source,bash]
----
$ cat script.clj
#!/bin/sh

#_(
   "exec" "bb" "$0" hello "$@"
   )

(prn *command-line-args*)

./script.clj 1 2 3
("hello" "1" "2" "3")
----

=== Current file path

The var `*file*` contains the full path of the file that is currently
being executed:

[source,bash]
----
$ cat example.clj
(prn *file*)

$ bb example.clj
"/Users/borkdude/example.clj"
----

=== Parsing command line arguments

Command-line arguments can be retrieved using `*command-line-args*`. If you
want to parse command line arguments, you can use the built-in
`babashka.cli` namespace:

[source,clojure]
----
(require '[babashka.cli :as cli])

(def cli-options {:port {:default 80 :coerce :long}
                  :help {:coerce :boolean}

(prn (:options (cli/parse-opts *command-line-args* {:spec cli-options})))
----

[source,bash]
----
$ bb script.clj
{:port 80}
$ bb script.clj --port 1223
{:port 1223}
$ bb script.clj --help
{:port 80, :help true}
----

Note that https://github.com/clojure/tools.cli[clojure.tools.cli] is also built-in to babashka.

=== Classpath

It is recommended to use `bb.edn` to control what directories and libraries are
included on babashka's classpath. See <<project-setup>>

If you want a lower level to control
babashka's classpath, without the usage of `bb.edn` you can use the
`--classpath` option that will override the classpath.  Say we have a file
`script/my/namespace.clj`:

[source,clojure]
----
(ns my.namespace)
(defn -main [& args]
  (apply println "Hello from my namespace!" args))
----

Now we can execute this main function with:

[source,clojure]
----
$ bb --classpath script --main my.namespace 1 2 3
Hello from my namespace! 1 2 3
----

If you have a larger script with a classic Clojure project layout like

[source,bash]
----
$ tree -L 3
├── deps.edn
├── README
├── src
│   └── project_namespace
│       ├── main.clj
│       └── utilities.clj
└── test
    └── project_namespace
        ├── test_main.clj
        └── test_utilities.clj
----

then you can tell babashka to include both the `src` and `test` folders
in the classpath and start a socket REPL by running:

[source,bash]
----
$ bb --classpath src:test socket-repl 1666
----

If there is no `--classpath` argument, the `BABASHKA_CLASSPATH` environment
variable will be used. If that variable isn't set either, babashka will use
`:deps` and `:paths` from `bb.edn`.

Also see the link:#babashka_classpath[babashka.classpath]
namespace which allows dynamically adding to the classpath.

The namespace link:#babashkadeps[babashka.deps] integrates
https://github.com/clojure/tools.deps.alpha[tools.deps] with babashka and allows
you to set the classpath using a `deps.edn` map.

[[main-function]]
=== Invoking a main function

A main function can be invoked with `-m` or `--main` like shown above. When
given the argument `foo.bar`, the namespace `foo.bar` will be required and the
function `foo.bar/-main` will be called with command line arguments as strings.

Since babashka 0.3.1 you may pass a fully qualified symbol to `-m`:

[source,clojure]
----
$ bb -m clojure.core/prn 1 2 3
"1" "2" "3"
----

so you can execute any function as a main function, as long as it accepts
the number of provided arguments.

When invoking `bb` with a main function, the expression `(System/getProperty
"babashka.main")` will return the name of the main function.

=== Preloads

The environment variable `BABASHKA_PRELOADS` allows to define code that
will be available in all subsequent usages of babashka.

[source,bash]
----
BABASHKA_PRELOADS='(defn foo [x] (+ x 2))'
BABASHKA_PRELOADS=$BABASHKA_PRELOADS' (defn bar [x] (* x 2))'
export BABASHKA_PRELOADS
----

Note that you can concatenate multiple expressions. Now you can use
these functions in babashka:

[source,bash]
----
$ bb '(-> (foo *input*) bar)' <<< 1
6
----

You can also preload an entire file using `load-file`:

[source,bash]
----
export BABASHKA_PRELOADS='(load-file "my_awesome_prelude.clj")'
----

Note that `*input*` is not available in preloads.

include::usage/repl.adoc[]

include::usage/io-flags.adoc[]

=== Uberscript

The `--uberscript` option collects the expressions in
`BABASHKA_PRELOADS`, the command line expression or file, the main
entrypoint and all required namespaces from the classpath into a single
file. This can be convenient for debugging and deployment.

Here is an example that uses a function from the
https://github.com/clj-commons/fs[clj-commons/fs] library.

Let's first set the classpath:

[source,clojure]
----
$ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {clj-commons/fs {:mvn/version "1.6.307"}}}')
----

Write a little script, say `glob.clj`:

[source,clojure]
----
(ns glob (:require [me.raynes.fs :as fs]))

(run! (comp println str)
      (fs/glob (first *command-line-args*)))
----

For testing, we'll make a file which we will find using the glob function:

[source,bash]
----
$ touch README.md
----

Now we can execute the script which uses the library:

[source,bash]
----
$ time bb glob.clj '*.md'
/private/tmp/glob/README.md
bb glob.clj '*.md'   0.03s  user 0.01s system 88% cpu 0.047 total
----

Producing an uberscript with all required code:

[source,bash]
----
$ bb uberscript glob-uberscript.clj -f glob.clj
----

To prove that we don't need the classpath anymore:

[source,bash]
----
$ unset BABASHKA_CLASSPATH
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.03s  user 0.02s system 93% cpu 0.049 total
----

Caveats:

* _Dynamic requires_. Building uberscripts works by running top-level
`ns` and `require` forms. The rest of the code is not evaluated. Code
that relies on dynamic requires may not work in an uberscript.
* _Resources_. The usage of `io/resource` assumes a classpath, so when
this is used in your uberscript, you still have to set a classpath and
bring the resources along.

If any of the above is problematic for your project, using an
link:#uberjar[uberjar] is a good alternative.

==== Carve

Uberscripts can be optimized by cutting out unused vars with
https://github.com/borkdude/carve[carve].

[source,bash]
----
$ wc -l glob-uberscript.clj
     583 glob-uberscript.clj
$ carve --opts '{:paths ["glob-uberscript.clj"] :aggressive true :silent true}'
$ wc -l glob-uberscript.clj
     105 glob-uberscript.clj
----

Note that the uberscript became 72% shorter. This has a beneficial
effect on execution time:

[source,bash]
----
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.02s  user 0.01s system 84% cpu 0.034 total
----

=== Uberjar

Babashka can create uberjars from a given classpath and optionally a
main method:

[source,clojure]
----
$ cat bb/foo.clj
(ns foo)
(defn -main [& args] (prn :hello))
$ cat bb.edn
{:paths ["bb"]}
$ bb uberjar foo.jar -m foo
$ bb foo.jar
:hello
----

=== System properties

Babashka sets the following system properties:

* `babashka.version`: the version string, e.g. `"1.2.0"`
* `babashka.main`: the `--main` argument
* `babashka.file`: the `--file` argument (normalized using
`.getAbsolutePath`)

=== Data readers

Data readers can be enabled by setting `*data-readers*` to a hashmap of
symbols to functions or vars:

[source,clojure]
----
$ bb -e "(set! *data-readers* {'t/tag inc}) #t/tag 1"
2
----

To preserve good startup time, babashka does not scan the classpath for
`data_readers.clj` files.

=== Reader conditionals

Babashka supports reader conditionals by taking either the `:bb` or
`:clj` branch, whichever comes first. NOTE: the `:clj` branch behavior
was added in version 0.0.71, before that version the `:clj` branch was
ignored.

[source,clojure]
----
$ bb -e "#?(:bb :hello :clj :bye)"
:hello

$ bb -e "#?(:clj :bye :bb :hello)"
:bye

$ bb -e "[1 2 #?@(:bb [] :clj [1])]"
[1 2]
----

=== Invoking clojure

Babashka bundles https://github.com/borkdude/deps.clj[deps.clj] for invoking a
`clojure` JVM process:

[source,clojure]
----
$ bb clojure -M -e "*clojure-version*"
{:major 1, :minor 10, :incremental 1, :qualifier nil}
----

See the link:#_clojure[clojure] function in the
link:#babashkadeps[babashka.deps] namespace for programmatically invoking
clojure.
